MatchData Admin Maintenance
JonathanBooker912/OC-Esports-System-Backend pull request #21
Opened 2023-10-31 18:37 UTC by KyleD0711

Finally finished the matchdata stuff

2023-10-31 20:06 UTC, JonathanBooker912 commented on app/controllers/metric.controller.js
> +  await metricUtils
Can you add an optional query parameter here to filter metrics by type? I.e. get only match metrics or get only player metrics

2023-10-31 20:06 UTC, JonathanBooker912 requested changes
Plz

2023-10-31 20:21 UTC, KyleD0711 commented on app/controllers/metric.controller.js
> +  await metricUtils
Completed

2023-11-01 19:03 UTC, JonathanBooker912 approved these changes
ehe

2023-11-01 19:04 UTC, merged